.PHONY: all clean install uninstall

all:
	cd c11thrd && $(MAKE) $(MAKECMDGOALS)
	cd tcptest && $(MAKE) $(MAKECMDGOALS)

clean:
	cd c11thrd && $(MAKE) $(MAKECMDGOALS)
	cd tcptest && $(MAKE) $(MAKECMDGOALS)

install:

uninstall:
